### ISSUE TITLE
Оформление исходного кода

### ISSUE THREAD

**Issue by AleshaShch** [Rinarium/Wrink#2]
Доброго времени суток. Обратите внимание на порядок подключения модулей в файлах, а в частности: [models.py](https://github.com/Rinarium/Wrink/blob/master/Source/post/models.py) и [views.py](https://github.com/Rinarium/Wrink/blob/master/Source/post/views.py).  Привожу ссылку на стандарт, который вы используете,- [PEP 8](https://www.python.org/dev/peps/pep-0008/).

**Comment by Rinarium** [comment]
Добрый вечер. Да, вы правы. Ваши замечания учтены и исправлены в последнем [коммите](https://github.com/Rinarium/Wrink/commit/d019c889c311167fa530c80e54988f9dee57b3ef). Спасибо!
